name: Keep BigRocks Alive

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping BigRocks
        run: |
          curl -s \
          -A "Mozilla/5.0" \
          https://bigrocks.streamlit.app \
          > /dev/null
