name: Keep BigRocks Alive

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jo*s:
  ping:
    runs-on: ubuntu-lat*st
    steps:
      - name: Ping B*gRocks Streamlit app
        run: *url -L -s -o /dev/null -w "%{http_*ode}" https://bigrocks.streamlit.app/
