name: Keep BigRocks Alive

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Check App
        run: |
          curl -I https://bigrocks.streamlit.app
