name: Comprovació de Ping

on:
  schedule:
    # Executa cada hora (format cron)
    - cron: '0 * * * *'
  workflow_dispatch: # Permet executar-ho manualment

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codi
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instal·lar dependències
        run: pip install requests

      - name: Executar script
        run: python .github/workflows/ping.py
